# Laptop-specific Umbriel settings (built-in eDP-2 panel).

[layout]
mode = "scrolling"

[output."eDP-2"]
# mode = "2560x1440@144"
# position = [0, 0]
scale = 1.50
vrr = "fullscreen"            # "disabled" (default), "always", or "fullscreen"
workspaces = ["browser", "term", "comms", "games"]

[keybinds]
"XF86MonBrightnessUp" = "spawn:noctalia msg brightness-up eDP-2 10"
"XF86MonBrightnessDown" = "spawn:noctalia msg brightness-down eDP-2 10"
