[colors]
background = "#ccd0daF0"
text_primary = "#4c4f69FF"
text_muted = "#6c6f85FF"
accent_primary = "#8839efFF"
accent_secondary = "#fe640bFF"
warning = "#40a02bFF"
error = "#d20f39FF"

[appearance]
border_focused = "#8839efFF"
border_unfocused = "#ccd0daFF"
scratchpad_border_focused = "#40a02bFF"
scratchpad_border_unfocused = "#afd7a7FF"
outer_border_color = "#eff1f5FF"
insert_hint_color = "#40a02b80"
backdrop_color = "#ccd0daFF"

[overview]
background_tint = "#eff1f530"
